# Generated by Django 5.2.1 on 2025-05-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mecanico',
            old_name='especialida',
            new_name='especialidad',
        ),
        migrations.AlterField(
            model_name='mecanico',
            name='codigo_trabajador',
            field=models.IntegerField(unique=True),
        ),
    ]
